###
POST http://localhost:3020/api/signup HTTP/1.1
Content-Type: application/json

{
    "nombre": "Martha",
    "apellidos": "Gomez",
    "email": "gmartha@gmail.com",
    "password": "proteinas",
    "confirmarPassword": "proteinas"
}